name: record_iterable_utils
description: A Dart package providing extension methods and utility functions for working with iterable records
version: 0.1.0
repository: https://github.com/K9i-0/record_iterable_utils

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
